version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: estudo-sqlserver
    ports:
      - 1434:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=numsey#2021
    labels:
      type: "estudo"

volumes:
  mssqldata: